on: push

permissions:
    contents: write

jobs:
    npm-build:
        name: npm-build工作
        runs-on: ubuntu-latest
        
        steps:
        - name: 读取仓库内容
          uses: actions/checkout@v4
        
        -  name: 登录DockerHub
           uses: docker/login-action@v3
           with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         
        - name: 构建并推送镜像到DockerHub
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: yyn/react-app:latest